openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /todos:
    get:
      summary: Returns a list of todos.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
components:
  schemas:
    ToDo:
      type: object
      title: ToDo
      properties:
        id:
          type: integer
        title:
          type: string
          maxLength: 64
          minLength: 1
        description:
          type: string
          maxLength: 256
          minLength: 1
        isComplete:
          type: boolean
      required:
        - id
        - title
        - isComplete
