/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 * OpenAPI spec version: 0.1.9
 */
export interface ToDo {
  id: number;
  title: string;
  description?: string;
  isComplete: boolean;
}
